---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[ubumirror]
